version: '3.8'

services:
  web:
    image: nginx:latest
    container_name: nginx_web_server
    ports:
      - "80:80"
    volumes:
      - ./nginx:/usr/share/nginx/html
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: mysql_database
    environment:
      MYSQL_ROOT_PASSWORD: roottpassword132!~@
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: roottpassword132!~@
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
    db_data:
